name: Build APK

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Dependencies
        run: |

          rm -rf node_modules
          rm -f package-lock.json

          npm install --force

          npm install \
          tailwindcss \
          @tailwindcss/postcss \
          postcss \
          autoprefixer \
          --save-dev \
          --force

      - name: Build Web
        run: |

          npm run build

      - name: Install Capacitor
        run: |

          npm install @capacitor/core --force
          npm install @capacitor/cli --save-dev --force
          npm install @capacitor/android --force

      - name: Sync Capacitor
        run: |

          npx cap sync android

      - name: Force Java 17
        run: |

          find android -type f -name "*.gradle" -exec sed -i \
          -e 's/VERSION_21/VERSION_17/g' \
          -e 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' \
          -e 's/sourceCompatibility = 21/sourceCompatibility = 17/g' \
          -e 's/targetCompatibility = 21/targetCompatibility = 17/g' \
          -e 's/JavaLanguageVersion.of(21)/JavaLanguageVersion.of(17)/g' \
          {} +

      - name: Build APK
        run: |

          cd android

          chmod +x gradlew

          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AETHER-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk/
